title: "Tweak Suggestion"
labels: ["tweak-suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a tweak to existing content!

        Please ensure this is about tweaking existing rebase content NOT related to our previous codebase.
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please ensure you've checked the following before submitting
      options:
        - label: This is NOT about content from our previous codebase
          required: true
        - label: This is about modifying existing content, not adding new features
          required: true
  - type: textarea
    id: about-tweak
    attributes:
      label: About the Tweak
      description: Provide general information about the tweak you're suggesting
      placeholder: |
        Please include:
        - What you want to tweak
        - Why this tweak would be beneficial
        - Any supporting images or information
    validations:
      required: true
  - type: textarea
    id: current-content
    attributes:
      label: Current Content Location
      description: Help us find the content you want to tweak
      placeholder: |
        Please include:
        - Location in codebase (file paths, class paths, text, images, urls, etc.)
        - How the content currently works
        - Screenshots/videos of current behavior if applicable
        - Any relevant code snippets
    validations:
      required: true
  - type: textarea
    id: suggested-tweak
    attributes:
      label: Suggested Tweak
      description: Provide a detailed explanation of your suggested changes compared to the current content
      placeholder: |
        Use this in case the "About the Tweak" section is not enough to explain the suggested changes.
        Please include:
        - Detailed description of proposed changes
        - How it should work after the tweak
        - Any examples or mockups of the desired behavior
        - Potential implementation suggestions
    validations:
      required: false
  - type: textarea
    id: port-info
    attributes:
      label: Is it a Port?
      description: If this is a port from another codebase (NOT our previous codebase), provide details
      placeholder: |
        If this is a port, please include:
        - Source codebase/repository
        - Location in source (file paths, class paths, text, images, urls, etc.)
        - Any relevant code snippets
        - Screenshots/videos if applicable

        Leave this section blank if this is not a port.
    validations:
      required: false

